name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r25b
        local-cache: true
    - name: Setup local.properties
      run: echo "ndk.dir=${{ steps.setup-ndk.outputs.ndk-path }}" >> ./local.properties; echo "sdk.dir=$ANDROID_SDK_ROOT" >> ./local.properties
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      run: ./tools/build-debug; ls -lah term/build/outputs/apk/debug/*
    - uses: actions/upload-artifact@v3
      with:
        name: apk-file
        path: term/build/outputs/apk/debug/
